from __future__ import annotations

from src.mcp_shared.agent_contracts import (
    DELETE,
    EXECUTE,
    HARDWARE,
    MEDIA_INPUT,
    META,
    READ,
    SANDBOX_EXECUTE,
    VALID_TOOL_CATEGORIES,
    WEB,
    WRITE,
    ToolCategory,
)

# Compatibility fallback for code that constructs PermissionPolicy without a registry.
# LocalToolRuntime derives the live source of truth from registered ToolDefinition objects.
LEGACY_TOOL_CATEGORIES: dict[str, str] = {
    "pwd": META,
    "readfile": READ,
    "listdir": READ,
    "exists": READ,
    "fileinfo": READ,
    "search_code": READ,
    "find_files": READ,
    "read_lines": READ,
    "list_tree": READ,
    "get_python_symbols": READ,
    "find_definition": READ,
    "find_references": READ,
    "extract_imports": READ,
    "syntax_check_python": READ,
    "python_compile_check": READ,
    "writefile": WRITE,
    "appendfile": WRITE,
    "movefile": WRITE,
    "mkdir": WRITE,
    "replace_in_file": WRITE,
    "replace_lines": WRITE,
    "run_python_file": EXECUTE,
    "python": EXECUTE,
    "python_interpreter": EXECUTE,
    "run_module": EXECUTE,
    "run_tests": EXECUTE,
    "lint_python": EXECUTE,
    "format_python": EXECUTE,
    "node_syntax_check": EXECUTE,
    "node_run_script": EXECUTE,
    "node_test": EXECUTE,
    "node_lint": EXECUTE,
    "node_format": EXECUTE,
    "ts_typecheck": EXECUTE,
    "dotnet_restore": EXECUTE,
    "dotnet_build": EXECUTE,
    "dotnet_test": EXECUTE,
    "dotnet_run": EXECUTE,
    "git_status": READ,
    "git_diff": READ,
    "git_log": READ,
    "git_show": READ,
    "git_branches": READ,
    "git_blame": READ,
    "git_ls_files": READ,
    "kv_get": READ,
    "kv_list": READ,
    "kv_set": WRITE,
    "kv_delete": WRITE,
    "kv_clear_expired": WRITE,
    "deletefile": DELETE,
    "deletedir": DELETE,
    "serial_list_ports": HARDWARE,
    "serial_send": HARDWARE,
    "image_describe": MEDIA_INPUT,
    "web_search": WEB,
    "web_fetch": WEB,
    "sandbox_run": SANDBOX_EXECUTE,
}
