from .handlers_cache import (
    handle_cache_get,
    handle_cache_list,
    handle_cache_set,
)
from .handlers_core import (
    handle_clear,
    handle_exit,
    handle_health,
    handle_info,
    handle_mode,
    handle_output,
    handle_perms,
    handle_prompts,
    handle_questions,
    handle_status,
    handle_thinking,
    handle_tools,
)
from .handlers_fs import (
    handle_files,
    handle_find,
    handle_head,
    handle_ls,
    handle_pwd,
    handle_read,
    handle_tree,
)
from .handlers_help import handle_help
from .handlers_sessions import (
    handle_compact,
    handle_new,
    handle_resume,
    handle_save,
    handle_sessions,
)
from .models import (
    ARG_COMMAND,
    ARG_GLOB,
    ARG_INT,
    ARG_PATH,
    ARG_TEXT,
    SlashCommand,
)
from .router import SlashCommandRouter


def create_default_router() -> SlashCommandRouter:
    commands = [
        SlashCommand(
            name="help",
            summary="Muestra comandos slash disponibles y ejemplos.",
            usage="/help [comando]",
            category="Imprescindibles",
            handler=handle_help,
            examples=("/help", "/help read"),
            arg_kinds=(ARG_COMMAND, ARG_COMMAND),
        ),
        SlashCommand(
            name="info",
            summary="Muestra la configuracion actual del cliente.",
            usage="/info",
            category="Imprescindibles",
            handler=handle_info,
        ),
        SlashCommand(
            name="health",
            summary="Verifica conectividad con el servidor.",
            usage="/health",
            category="Imprescindibles",
            handler=handle_health,
        ),
        SlashCommand(
            name="tools",
            summary="Lista las tools visibles segun permisos.",
            usage="/tools",
            category="Imprescindibles",
            handler=handle_tools,
        ),
        SlashCommand(
            name="prompts",
            summary="Lista los prompts disponibles en el runtime.",
            usage="/prompts",
            category="Imprescindibles",
            handler=handle_prompts,
        ),
        SlashCommand(
            name="perms",
            summary="Muestra los permisos activos del runtime.",
            usage="/perms",
            category="Imprescindibles",
            handler=handle_perms,
        ),
        SlashCommand(
            name="mode",
            summary="Consulta o cambia auto-routing: auto, direct o team.",
            usage="/mode [auto|direct|team]",
            category="Imprescindibles",
            handler=handle_mode,
            examples=("/mode", "/mode direct", "/mode team", "/mode auto"),
            arg_kinds=(ARG_TEXT,),
        ),
        SlashCommand(
            name="status",
            summary="Muestra sesion, servidor, permisos y trazas activas.",
            usage="/status",
            category="Imprescindibles",
            handler=handle_status,
        ),
        SlashCommand(
            name="thinking",
            summary="Alterna o fija la visibilidad del reasoning.",
            usage="/thinking [on|off|toggle]",
            category="Imprescindibles",
            handler=handle_thinking,
            examples=("/thinking", "/thinking on", "/thinking off"),
            arg_kinds=(ARG_TEXT,),
        ),
        SlashCommand(
            name="questions",
            summary="Controla si las preguntas del agente se responden en auto o manual.",
            usage="/questions [auto|manual|toggle|status]",
            category="Imprescindibles",
            handler=handle_questions,
            examples=("/questions", "/questions auto", "/questions manual"),
            arg_kinds=(ARG_TEXT,),
        ),
        SlashCommand(
            name="output",
            summary="Consulta o cambia el nivel de detalle de salida.",
            usage="/output [minimal|normal|debug]",
            category="Imprescindibles",
            handler=handle_output,
            examples=("/output", "/output minimal", "/output debug"),
            arg_kinds=(ARG_TEXT,),
        ),
        SlashCommand(
            name="sessions",
            summary="Lista sesiones persistentes recientes.",
            usage="/session list [limite]",
            category="Sesiones",
            handler=handle_sessions,
            examples=("/session list", "/session list 5", "/sessions 5"),
            arg_kinds=(ARG_INT,),
            route=("session", "list"),
        ),
        SlashCommand(
            name="resume",
            summary="Reanuda una sesion persistente por ID.",
            usage="/session resume <session_id>",
            category="Sesiones",
            handler=handle_resume,
            examples=(
                "/session resume 00000000-0000-0000-0000-000000000000",
                "/resume 00000000-0000-0000-0000-000000000000",
            ),
            arg_kinds=(ARG_TEXT,),
            route=("session", "resume"),
        ),
        SlashCommand(
            name="new",
            summary="Crea una sesion persistente nueva y limpia el contexto.",
            usage="/session new [titulo]",
            category="Sesiones",
            handler=handle_new,
            examples=("/session new", "/session new refactor cli", "/new refactor cli"),
            arg_kinds=(ARG_TEXT,),
            route=("session", "new"),
        ),
        SlashCommand(
            name="save",
            summary="Guarda la conversacion actual en la sesion activa.",
            usage="/session save [titulo]",
            category="Sesiones",
            handler=handle_save,
            examples=(
                "/session save",
                "/session save investigacion sandbox",
                "/save investigacion sandbox",
            ),
            arg_kinds=(ARG_TEXT,),
            route=("session", "save"),
        ),
        SlashCommand(
            name="clear",
            summary="Limpia la conversacion actual del REPL.",
            usage="/clear",
            category="Imprescindibles",
            handler=handle_clear,
        ),
        SlashCommand(
            name="compact",
            summary="Resume la conversacion y conserva solo el contexto esencial.",
            usage="/session compact [enfoque]",
            category="Sesiones",
            handler=handle_compact,
            examples=(
                "/session compact",
                "/session compact conserva decisiones tecnicas, archivos tocados y pendientes",
                "/compact conserva decisiones tecnicas, archivos tocados y pendientes",
            ),
            arg_kinds=(ARG_TEXT,),
            route=("session", "compact"),
        ),
        SlashCommand(
            name="cache-get",
            summary="Lee una entrada del KV cache local.",
            usage="/cache get <namespace> <key>",
            category="Cache",
            handler=handle_cache_get,
            examples=("/cache get repo last_scan", "/cache-get repo last_scan"),
            arg_kinds=(ARG_TEXT, ARG_TEXT),
            route=("cache", "get"),
        ),
        SlashCommand(
            name="cache-set",
            summary="Escribe una entrada de texto en el KV cache local.",
            usage="/cache set <namespace> <key> <value>",
            category="Cache",
            handler=handle_cache_set,
            examples=("/cache set repo last_scan ok", "/cache-set repo last_scan ok"),
            arg_kinds=(ARG_TEXT, ARG_TEXT, ARG_TEXT),
            route=("cache", "set"),
        ),
        SlashCommand(
            name="cache-list",
            summary="Lista entradas del KV cache local.",
            usage="/cache list [namespace]",
            category="Cache",
            handler=handle_cache_list,
            examples=("/cache list", "/cache list repo", "/cache-list repo"),
            arg_kinds=(ARG_TEXT,),
            route=("cache", "list"),
        ),
        SlashCommand(
            name="exit",
            summary="Sale del REPL.",
            usage="/exit",
            category="Imprescindibles",
            handler=handle_exit,
        ),
        SlashCommand(
            name="pwd",
            summary="Muestra la carpeta base activa.",
            usage="/pwd",
            category="Inspeccion Rapida",
            handler=handle_pwd,
        ),
        SlashCommand(
            name="ls",
            summary="Lista archivos y carpetas en una ruta.",
            usage="/ls [ruta]",
            category="Inspeccion Rapida",
            handler=handle_ls,
            examples=("/ls", "/ls src"),
            arg_kinds=(ARG_PATH,),
        ),
        SlashCommand(
            name="tree",
            summary="Muestra el arbol de una ruta.",
            usage="/tree [ruta] [depth]",
            category="Inspeccion Rapida",
            handler=handle_tree,
            examples=("/tree", "/tree src 2"),
            arg_kinds=(ARG_PATH, ARG_INT),
        ),
        SlashCommand(
            name="read",
            summary="Lee un archivo completo.",
            usage="/read <archivo>",
            category="Inspeccion Rapida",
            handler=handle_read,
            examples=("/read src/mcp_client/app/client.py",),
            arg_kinds=(ARG_PATH,),
        ),
        SlashCommand(
            name="head",
            summary="Lee las primeras lineas de un archivo.",
            usage="/head <archivo> [n]",
            category="Inspeccion Rapida",
            handler=handle_head,
            examples=(
                "/head src/mcp_client/app/client.py",
                "/head src/mcp_client/app/client.py 40",
            ),
            arg_kinds=(ARG_PATH, ARG_INT),
        ),
        SlashCommand(
            name="find",
            summary="Busca texto en el codigo.",
            usage="/find <texto> [glob]",
            category="Inspeccion Rapida",
            handler=handle_find,
            examples=('/find "MCPClient"', '/find "writefile" *.py'),
            arg_kinds=(ARG_TEXT, ARG_GLOB),
        ),
        SlashCommand(
            name="files",
            summary="Busca archivos por patron.",
            usage="/files <glob>",
            category="Inspeccion Rapida",
            handler=handle_files,
            examples=("/files *.py", "/files src/mcp_client/*.py"),
            arg_kinds=(ARG_GLOB,),
        ),
    ]
    return SlashCommandRouter(commands)
